# 基础镜像
FROM swr.zhydc-nyyjy-1.r410.cnooc/public-image-swr/nginx-arm:1.23.1
# author
MAINTAINER cnooc

# 挂载目录
VOLUME /home/cnooc/projects/cnooc-ui
# 创建目录
RUN mkdir -p /home/cnooc/projects/cnooc-ui
# 指定路径
WORKDIR /home/cnooc/projects/cnooc-ui
# 复制conf文件到路径
COPY ./docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/cnooc/projects/cnooc-ui
